import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";

import "./globals.css";

export const normal = Noto_Sans_KR({
  weight: "400",
  display: "fallback",
  style: "normal",
  subsets: ["cyrillic"],
  variable: "--noto-sans_KR-normal",
  fallback: ["system-ui"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={normal.className}>{children}</body>
    </html>
  );
}
